widgets:
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: toc
        index: true
        collapsed: false
        depth: 5

sidebar:
    # Left sidebar configurations
    left:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false
    # Right sidebar configurations
    right:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: true